-- CREATE TABLE
ALTER TABLE EARTHQUAKEDATA DROP PRIMARY KEY CASCADE;
DROP TABLE EARTHQUAKEDATA CASCADE CONSTRAINTS;

CREATE TABLE EARTHQUAKEDATA
(  
  DEVID   VARCHAR2(5)		        NOT NULL, 
  OBSDATE   TIMESTAMP(6)        NOT NULL,  
  OBSVALUE  NUMBER(8,2)         NOT NULL
);

ALTER TABLE EARTHQUAKEDATA ADD (
  CONSTRAINT PK_EARTHQUAKEDATA
    PRIMARY KEY (DEVID, OBSDATE)
);

-- GENERATE SYNTHETIC DATA
DECLARE
  DEVID VARCHAR2(5);
  OBSDATE DATE;
  OBSVALUE NUMBER(8,2);  
BEGIN
  FOR t IN 1..10 LOOP
  SELECT TO_DATE('2000-01-01','yyyy-mm-dd') INTO OBSDATE FROM DUAL; 
    FOR i IN 1..100000 LOOP
      SELECT  t INTO DEVID FROM DUAL;       
      SELECT (DBMS_RANDOM.VALUE(1,40)) INTO OBSVALUE FROM DUAL;   
       SELECT OBSDATE+1/24/60 INTO OBSDATE FROM DUAL;     --ADD 1 MINUTE   
      INSERT INTO EARTHQUAKEDATA(DEVID, OBSDATE, OBSVALUE)
      VALUES (DEVID, OBSDATE, OBSVALUE);
     END LOOP;
     COMMIT;
     DBMS_OUTPUT.PUT_LINE('Inserted ' || (t+1) || '00,000 records. ' || (t+1) || '0% finished.'); 
   END LOOP;
   COMMIT;
END;
/